name: test-evilfreelancer-routeros

on:
  workflow_dispatch:
    inputs:
      rosver:
        description: 'RouterOS Version'
        required: true
      start_path:
        description: 'Starting path (space seperated)'
        required: false

jobs:
  ros-in-action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v1

#    - name: Log in to Docker Hub
#      uses: docker/login-action@v3
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Run Docker Compose
      run: |
        echo "version: '3'
        services:
          routeros:
            image: evilfreelancer/docker-routeros
            restart: unless-stopped
            cap_add:
              - NET_ADMIN
            devices:
              - /dev/net/tun
              - /dev/kvm
            environment:
              - ROUTEROS_VERSION="${{ github.event.inputs.rosver }}"
            ports:
              - 9180:80" > docker-compose.yml
        docker-compose up -d

    - name: Wait For `curl`
      run: |
        echo "Waiting for the HTTP server to start..."
        for i in {1..1000}; do
          if curl -S --fail http://localhost:9180/; then
            echo "Server is up!"
            exit 0
          else
            echo "Server not ready yet. Retrying in 10 seconds..."
            sleep 10
          fi
        done
        echo "Server did not start within expected time."
        exit 1

    - name: Test HTTP Server with curl
      run: curl -S --fail http://admin@localhost:9180/rest/ip/address

    - name: Setup Bun Runtime
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 'latest' 

    - name: Run RAML Generator Code with Bun
      run: |
        bun install js-yaml raml2html raml2html-slate-theme
        bun rest2raml.js ${{ github.event.inputs.start_path }}
        find . -name raml2html
        ./node_modules/.bin/raml2html --theme raml2html-slate-theme ros-rest*.raml > ros-rest-generated.html
      env:
        URLBASE: http://localhost:9180/rest 
        BASICAUTH: "admin:" 

    - name: Save Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: |
          ros-rest*
          ros-inspect*
          ros-rest-generated*

    - name: Cleanup Running Docker
      run: docker-compose down
